site_name: Сайт | Маликов Артем
site_description: Это мой первый сайт, созданный в рамках курсовой работы на курсе ICT с использованием технологии MkDocs по предмету "Введение в веб технологии"
site_author: Артем Маликов
site_url: http://127.0.0.1:8000/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - navigation.expand
    - content.code.copy
  palette:
    primary: red
    accent: purple

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Контакты: contacts.md
  - Достижения: achievements.md

markdown_extensions:
  - admonition
  - tables
  - attr_list

copyright: Copyright &copy; 2026 Маликов Артем
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/Artem_Malikov
      name: Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/artemmalickov2015-cmyk
      name: GitHub